server:
  port: 21010

spring:

#datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      url: jdbc:mysql://114.67.104.110:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: MhxzKhl@123
      fail-fast: true
      remove-abandoned: true
      remove-abandoned-timeout-millis: 60000
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      validation-query: SELECT 1 FROM DUAL
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      max-pool-prepared-statement-per-connection-size: 20

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

